#Question 2: Top Agencies' Market Share in Real Estate Revenue
#Which two or three agencies(duopoly) have been the major market leader in the real estate business? What percentage of total share do they own in the entire revenue?
#To determine which agencies have been the major market leaders in the real estate business, we composed a query that calculates the total revenue generated by each agency. The query identifies the top three agencies with the highest revenue and calculates their combined percentage of the total market share.

WITH AgencyRevenues AS (
SELECT
A.AgencyID,
A.AgencyName,
SUM(A.Revenue) AS TotalRevenue
FROM
AgencY A
GROUP BY
A.AgencyID, A.AgencyName
),
TotalMarketRevenue AS (
SELECT
SUM(TotalRevenue) AS OverallRevenue
FROM
AgencyRevenues
)
SELECT
AR.AgencyID,
AR.AgencyName,
AR.TotalRevenue,
ROUND((AR.TotalRevenue / TMR.OverallRevenue) * 100,4) AS MarketSharePercentage
FROM
AgencyRevenues AR,
TotalMarketRevenue TMR
ORDER BY
AR.TotalRevenue DESC
FETCH FIRST 3 ROWS ONLY;

#The top three agencies that have been the major market leader in the real estate business are Compass, eXp Realty LLC and Green Banker.