#Question 1: Top 3 Realtors by Total Sales Volume and Market Share
#Which three realtors have sold the most volume(total sales in dollars) of houses in the database? What percentage do they make up in the entire volume of all realtors?
#To achieve this we composed a simple query that calculates the total sales volume for each realtor. The query then identifies the top 3 realtors with the highest sales volume and calculates the percentage of the entire volume these three realtors represent out of the total sales volume generated by all realtors in the database.

WITH AgentSales AS (
SELECT
A.AgentID,
A.FirstName,
A.LastName,
SUM(P.Price) AS TotalSales
FROM
Agent A
JOIN
Property P ON A.AgentID = P.AgentID
GROUP BY
A.AgentID, A.FirstName, A.LastName
),
TotalVolume AS (
SELECT
SUM(TotalSales) AS OverallVolume
FROM
AgentSales
)
SELECT
ASales.AgentID,
ASales.FirstName,
ASales.LastName,
ASales.TotalSales,
ROUND((ASales.TotalSales / TV.OverallVolume) * 100,4) AS PercentageOfTotal
FROM
AgentSales ASales,
TotalVolume TV
ORDER BY
ASales.TotalSales DESC
FETCH FIRST 3 ROWS ONLY;


#The results of this query are shown below. The top three realtors are Susan Breitenbach, Leslie McElwreath and Pollena Forsman. The table also displays the percentage they make up in the entire volume of all realtors.